main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.log_in, name='login'),
    path('logout', views.log_out, name='logout'),
    path('signup', views.signup, name='signup'),
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

def home(request):
    return render(request, 'main/home.html')

def log_in(request):
    if (request.method == "POST"):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        success = False
        if user is not None:
            login(request, user)
            success = True
            return render(request, 'main/home.html', {'success':success})
        
        else:
            
            return render(request, 'main/login.html', {'success':success})
    else:  
        return render(request, 'main/login.html')

def log_out(request):
    logout(request)
    return HttpResponseRedirect('/')

def signup(request):
    if(request.method == "POST"):
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.save()
        return HttpResponseRedirect('/login')
    else:
        return render(request, 'main/signup.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}
{% if user.is_authenticated %}
<div class="container">
  <div class="row text-center pt-5 mt-5">
    <div class="col">
      <h4 class="display-4">Hi, {{ user.username }}!</h4>
      <a href="{% url 'main:logout' %}" class="btn btn-danger mt-3">Log Out</a>
    </div>
  </div>
</div>
{% else %}
<div class="container">
  <div class="row text-center pt-5 mt-5">
    <div class="col">
      <h4 class="display-4">You are not logged in</h4>
      <a href="{% url 'main:login' %}" class="btn btn-success mt-3">Log In</a>
    </div>
  </div>
</div>


{% endif %}
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<form action="{% url 'main:login' %}" method="post">
    {% csrf_token %}
    <div class="container pt-5 mt-5">
        <div class="form-container">
            <h4 class="display-4 mb-3">Log in</h4>   
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                </div>
                <input type="text" class="form-control" placeholder="Username" name="username" id="username">
            </div>
    
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
                </div>
                <input type="password" class="form-control" placeholder="Password" name="password" id="password">
            </div>
            <button type="submit" class="btn btn-success mt-3">Log in</button>
        {% if success == False %}
        <p style="color: red;">Login Failed</p>
        {% endif %}
        <p></p>
        <p>Don't have an account? <a href="{% url 'main:signup' %}">Sign Up</a></p>
        </div>
    </div>
    
</form>
{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Signup</title>
{% endblock meta %}

{% block content %}
<form action="{% url 'main:signup' %}" method="post">
    {% csrf_token %}
    <div class="container pt-5 mt-5">
        <div class="form-container">
            <h4 class="display-4 mb-3">Create Account</h2>   
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                </div>
                <input type="text" class="form-control" placeholder="Username" name="username" id="username"><br>
            </div>
    
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-at"></i></span>
                </div>
                <input type="email" class="form-control" placeholder="E-mail" name="email" id="email"><br>
            </div>
    
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
                </div>
                <input type="password" class="form-control" placeholder="Password" name="password" id="password"><br>
            </div>
            <button type="submit" class="btn btn-success mt-3">Sign Up</button>
    
            <p></p>
            <p>Already have an account? <a href="{% url 'main:login' %}">Log in</a></p>
        </div>
    </div>
    
</form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS BOOTSTRAP -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- CSS Local -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/1594282c33.js" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body class="pb-5 mb-5">
  <!-- <h1>Hello, world!</h1> -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="{% url 'main:home' %}">Ghifari</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <!-- <a class="nav-item nav-link page-scroll" href="#home">Home <span class="sr-only">(current)</span></a> -->
          <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
        </div>
      </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>